version: '3'

networks:
  default:
    external:
      name: div-network

services:
  eureka:
    build: ./eureka-server
    image: demo-eureka-server
    ports:
      - 8080:8080 
    networks:
       default:
          ipv4_address: 192.168.100.2

  demo-python-sidecar:
    build: ./node-sidecar-service-demo
    image: demo-python-sidecar
    ports:
      - 8082:8082
    networks:
       default:
          ipv4_address: 192.168.100.3
    links:
      - eureka
      - friendlyhello

  friendlyhello:
    build: ./python-demo
    image: friendlyhello
    ports:
      - 4000:4000
    networks:
       default:
          ipv4_address: 192.168.100.4
    links:
      - eureka

  python-call-service:
    build: ./gin-ktor-compose-service
    image: python-call-service
    ports:
      - 8084:8084
    networks:
       default:
          ipv4_address: 192.168.100.5
    links:
      - eureka
      - demo-python-sidecar
      - friendlyhello
