server:
  port: 8084
spring:
  application:
    name: python-call-service

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://192.168.100.2:8080/eureka/}

ribbon:
  eureka:
    enabled: true
